CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260805214952_Inicial') THEN
    CREATE TABLE carga_archivo (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        nombre_archivo character varying(260) NOT NULL,
        ruta_archivo character varying(500),
        tamano_bytes bigint NOT NULL,
        usuario character varying(150) NOT NULL,
        fecha_registro timestamp with time zone NOT NULL,
        estado character varying(20) NOT NULL,
        fecha_fin timestamp with time zone,
        total_filas integer NOT NULL DEFAULT 0,
        filas_insertadas integer NOT NULL DEFAULT 0,
        filas_rechazadas integer NOT NULL DEFAULT 0,
        mensaje_error text,
        correlation_id character varying(50) NOT NULL,
        CONSTRAINT pk_carga_archivo PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260805214952_Inicial') THEN
    CREATE TABLE usuario (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        email character varying(150) NOT NULL,
        password_hash text NOT NULL,
        rol character varying(50) NOT NULL,
        activo boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT pk_usuario PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260805214952_Inicial') THEN
    CREATE TABLE carga_periodo (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        carga_archivo_id integer NOT NULL,
        periodo character varying(7) NOT NULL,
        estado character varying(20) NOT NULL,
        filas_insertadas integer NOT NULL DEFAULT 0,
        CONSTRAINT pk_carga_periodo PRIMARY KEY (id),
        CONSTRAINT fk_carga_periodo_carga_archivo_carga_archivo_id FOREIGN KEY (carga_archivo_id) REFERENCES carga_archivo (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260805214952_Inicial') THEN
    CREATE TABLE data_procesada (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        periodo character varying(7) NOT NULL,
        codigo_producto character varying(50) NOT NULL,
        nombre_producto character varying(200) NOT NULL,
        precio numeric(18,2) NOT NULL,
        carga_archivo_id integer NOT NULL,
        fecha_registro timestamp with time zone NOT NULL,
        CONSTRAINT pk_data_procesada PRIMARY KEY (id),
        CONSTRAINT fk_data_procesada_carga_archivo_carga_archivo_id FOREIGN KEY (carga_archivo_id) REFERENCES carga_archivo (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260805214952_Inicial') THEN
    CREATE TABLE detalle_carga_error (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        carga_archivo_id integer NOT NULL,
        numero_fila integer NOT NULL,
        periodo character varying(7),
        codigo_producto character varying(50),
        columna character varying(50),
        motivo character varying(40) NOT NULL,
        valor_crudo text,
        fecha_registro timestamp with time zone NOT NULL,
        CONSTRAINT pk_detalle_carga_error PRIMARY KEY (id),
        CONSTRAINT fk_detalle_carga_error_carga_archivo_carga_archivo_id FOREIGN KEY (carga_archivo_id) REFERENCES carga_archivo (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260805214952_Inicial') THEN
    CREATE TABLE refresh_token (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        usuario_id integer NOT NULL,
        token character varying(200) NOT NULL,
        expira_en timestamp with time zone NOT NULL,
        revocado_en timestamp with time zone,
        reemplazado_por character varying(200),
        CONSTRAINT pk_refresh_token PRIMARY KEY (id),
        CONSTRAINT fk_refresh_token_usuario_usuario_id FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260805214952_Inicial') THEN
    CREATE INDEX ix_carga_archivo_estado ON carga_archivo (estado);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260805214952_Inicial') THEN
    CREATE INDEX ix_carga_periodo_carga_archivo_id ON carga_periodo (carga_archivo_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260805214952_Inicial') THEN
    CREATE UNIQUE INDEX ux_carga_periodo_activo ON carga_periodo (periodo) WHERE estado = 'Aceptado';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260805214952_Inicial') THEN
    CREATE INDEX ix_data_procesada_carga_archivo_id ON data_procesada (carga_archivo_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260805214952_Inicial') THEN
    CREATE UNIQUE INDEX ux_data_procesada_periodo_codigo ON data_procesada (periodo, codigo_producto);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260805214952_Inicial') THEN
    CREATE INDEX ix_detalle_carga_error_carga_archivo_id ON detalle_carga_error (carga_archivo_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260805214952_Inicial') THEN
    CREATE UNIQUE INDEX ix_refresh_token_token ON refresh_token (token);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260805214952_Inicial') THEN
    CREATE INDEX ix_refresh_token_usuario_id ON refresh_token (usuario_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260805214952_Inicial') THEN
    CREATE UNIQUE INDEX ix_usuario_email ON usuario (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260805214952_Inicial') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260805214952_Inicial', '10.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260805215001_Procedimientos') THEN
    CREATE OR REPLACE FUNCTION sp_resolver_periodo(p_carga_id int, p_periodo varchar)
    RETURNS varchar
    LANGUAGE plpgsql
    AS $$
    DECLARE
        v_estado_otra varchar(20);
    BEGIN
        -- Serializa a los competidores por ESTE periodo hasta el fin de la transacción.
        PERFORM pg_advisory_xact_lock(hashtext(p_periodo));

        -- Una carga que murió sin terminar no puede reservar el periodo para siempre.
        -- Su reserva pasa a 'Bloqueado' (que es literalmente lo que le ocurrió) y el
        -- índice único parcial queda libre para la carga nueva.
        UPDATE carga_periodo cp
           SET estado = 'Bloqueado'
          FROM carga_archivo ca
         WHERE cp.carga_archivo_id = ca.id
           AND cp.periodo = p_periodo
           AND cp.estado = 'Aceptado'
           AND cp.carga_archivo_id <> p_carga_id
           AND ca.estado IN ('Fallida', 'Rechazada', 'Bloqueada');

        -- §C2: excluye la propia carga. Implementado literal, el consumidor
        -- encontraría su propia fila Pendiente y se auto-bloquearía.
        SELECT ca.estado INTO v_estado_otra
          FROM carga_periodo cp
          JOIN carga_archivo ca ON ca.id = cp.carga_archivo_id
         WHERE cp.periodo = p_periodo
           AND cp.estado = 'Aceptado'
           AND cp.carga_archivo_id <> p_carga_id
         LIMIT 1;

        IF v_estado_otra IN ('Cargado', 'Finalizado', 'Notificado') THEN
            RETURN 'YaCargado';
        ELSIF v_estado_otra IS NOT NULL THEN
            -- Otra carga Pendiente/EnProceso ya tomó el periodo.
            RETURN 'Bloqueado';
        END IF;

        -- ON CONFLICT: si el mensaje se reentrega (§C8), la reserva propia ya
        -- existe y la operación es inofensiva.
        INSERT INTO carga_periodo (carga_archivo_id, periodo, estado, filas_insertadas)
        VALUES (p_carga_id, p_periodo, 'Aceptado', 0)
        ON CONFLICT DO NOTHING;

        RETURN 'Libre';
    END;
    $$;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260805215001_Procedimientos') THEN
    CREATE OR REPLACE FUNCTION sp_insertar_data_procesada(
        p_carga_id  int,
        p_periodos  varchar[],
        p_codigos   varchar[],
        p_nombres   varchar[],
        p_precios   numeric[]
    )
    RETURNS int
    LANGUAGE plpgsql
    AS $$
    DECLARE
        v_insertadas int;
    BEGIN
        INSERT INTO data_procesada
            (periodo, codigo_producto, nombre_producto, precio, carga_archivo_id, fecha_registro)
        SELECT t.periodo, t.codigo, t.nombre, t.precio, p_carga_id, now()
          FROM unnest(p_periodos, p_codigos, p_nombres, p_precios)
            AS t(periodo, codigo, nombre, precio)
        ON CONFLICT (periodo, codigo_producto) DO NOTHING;

        GET DIAGNOSTICS v_insertadas = ROW_COUNT;

        -- La diferencia contra el tamaño del lote son los duplicados que ya
        -- estaban en base: el llamador los reporta como 'Existente'.
        RETURN v_insertadas;
    END;
    $$;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260805215001_Procedimientos') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260805215001_Procedimientos', '10.0.10');
    END IF;
END $EF$;
COMMIT;

