<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\CargaMasiva.Infrastructure\CargaMasiva.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\..\ServiceHost\ServiceHost.csproj" />
    <ProjectReference Include="..\..\..\Shared\Mensajeria\Mensajeria.csproj" />
    <ProjectReference Include="..\..\..\Shared\Persistencia\Persistencia.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
