// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistencia;

#nullable disable

namespace Persistencia.Migraciones
{
    [DbContext(typeof(RetoDbContext))]
    partial class RetoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Persistencia.CargaArchivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTimeOffset>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<int>("FilasInsertadas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("filas_insertadas");

                    b.Property<int>("FilasRechazadas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("filas_rechazadas");

                    b.Property<string>("MensajeError")
                        .HasColumnType("text")
                        .HasColumnName("mensaje_error");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("nombre_archivo");

                    b.Property<string>("RutaArchivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ruta_archivo");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamano_bytes");

                    b.Property<int>("TotalFilas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_filas");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("usuario");

                    b.HasKey("Id")
                        .HasName("pk_carga_archivo");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_carga_archivo_estado");

                    b.ToTable("carga_archivo", (string)null);
                });

            modelBuilder.Entity("Persistencia.CargaPeriodo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CargaArchivoId")
                        .HasColumnType("integer")
                        .HasColumnName("carga_archivo_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<int>("FilasInsertadas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("filas_insertadas");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("periodo");

                    b.HasKey("Id")
                        .HasName("pk_carga_periodo");

                    b.HasIndex("CargaArchivoId")
                        .HasDatabaseName("ix_carga_periodo_carga_archivo_id");

                    b.HasIndex("Periodo")
                        .IsUnique()
                        .HasDatabaseName("ux_carga_periodo_activo")
                        .HasFilter("estado = 'Aceptado'");

                    b.ToTable("carga_periodo", (string)null);
                });

            modelBuilder.Entity("Persistencia.DataProcesada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CargaArchivoId")
                        .HasColumnType("integer")
                        .HasColumnName("carga_archivo_id");

                    b.Property<string>("CodigoProducto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_producto");

                    b.Property<DateTimeOffset>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_producto");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("periodo");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio");

                    b.HasKey("Id")
                        .HasName("pk_data_procesada");

                    b.HasIndex("CargaArchivoId")
                        .HasDatabaseName("ix_data_procesada_carga_archivo_id");

                    b.HasIndex("Periodo", "CodigoProducto")
                        .IsUnique()
                        .HasDatabaseName("ux_data_procesada_periodo_codigo");

                    b.ToTable("data_procesada", (string)null);
                });

            modelBuilder.Entity("Persistencia.DetalleCargaError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CargaArchivoId")
                        .HasColumnType("integer")
                        .HasColumnName("carga_archivo_id");

                    b.Property<string>("CodigoProducto")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_producto");

                    b.Property<string>("Columna")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("columna");

                    b.Property<DateTimeOffset>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("motivo");

                    b.Property<int>("NumeroFila")
                        .HasColumnType("integer")
                        .HasColumnName("numero_fila");

                    b.Property<string>("Periodo")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("periodo");

                    b.Property<string>("ValorCrudo")
                        .HasColumnType("text")
                        .HasColumnName("valor_crudo");

                    b.HasKey("Id")
                        .HasName("pk_detalle_carga_error");

                    b.HasIndex("CargaArchivoId")
                        .HasDatabaseName("ix_detalle_carga_error_carga_archivo_id");

                    b.ToTable("detalle_carga_error", (string)null);
                });

            modelBuilder.Entity("Persistencia.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<string>("ReemplazadoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reemplazado_por");

                    b.Property<DateTimeOffset?>("RevocadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revocado_en");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("token");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_token_token");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_refresh_token_usuario_id");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("Persistencia.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rol");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_email");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Persistencia.CargaPeriodo", b =>
                {
                    b.HasOne("Persistencia.CargaArchivo", "CargaArchivo")
                        .WithMany("Periodos")
                        .HasForeignKey("CargaArchivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_carga_periodo_carga_archivo_carga_archivo_id");

                    b.Navigation("CargaArchivo");
                });

            modelBuilder.Entity("Persistencia.DataProcesada", b =>
                {
                    b.HasOne("Persistencia.CargaArchivo", "CargaArchivo")
                        .WithMany()
                        .HasForeignKey("CargaArchivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_data_procesada_carga_archivo_carga_archivo_id");

                    b.Navigation("CargaArchivo");
                });

            modelBuilder.Entity("Persistencia.DetalleCargaError", b =>
                {
                    b.HasOne("Persistencia.CargaArchivo", "CargaArchivo")
                        .WithMany()
                        .HasForeignKey("CargaArchivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_detalle_carga_error_carga_archivo_carga_archivo_id");

                    b.Navigation("CargaArchivo");
                });

            modelBuilder.Entity("Persistencia.RefreshToken", b =>
                {
                    b.HasOne("Persistencia.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_usuario_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Persistencia.CargaArchivo", b =>
                {
                    b.Navigation("Periodos");
                });
#pragma warning restore 612, 618
        }
    }
}
