<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.11" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Services\CargaMasiva\CargaMasiva.Application\CargaMasiva.Application.csproj" />
    <ProjectReference Include="..\..\src\Services\CargaMasiva\CargaMasiva.Infrastructure\CargaMasiva.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Services\Auth\Auth.Api\Auth.Api.csproj" />
    <ProjectReference Include="..\..\src\Services\Control\Control.Api\Control.Api.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\src\ServiceHost\ServiceHost.csproj" />
    <ProjectReference Include="..\..\src\Services\CargaMasiva\CargaMasiva.Api\CargaMasiva.Api.csproj" />
    <ProjectReference Include="..\..\src\Services\Notificaciones\Notificaciones.Api\Notificaciones.Api.csproj" />
  </ItemGroup>

</Project>
